language: node_js

os:
  - linux
  - osx
  - windows
  
if: os = linux OR osx
env: nodelatest=node

if: os = windows
env: nodelatest=latest

node_js:
  - env(nodelatest)
  - 'lts/*'

after_success: npm run coverage
