os:
  - linux
  - osx
  - windows

if: os = linux OR osx
language: node_js
node_js:
  - node
  - 'lts/*'

if: os = windows
language: node_js
node_js:
  - latest
  - 'lts/*'

after_success: npm run coverage
