language: node_js

os:
  - linux
  - osx
  - windows
  
env:
  - WIN_NODE_LATEST=latest
  - POSIX_NODE_LATEST=node

node_js:
  if: os = linux OR osx
  - env(POSIX_NODE_LATEST)
  
  if: os = windows
  - env(WIN_NODE_LATEST)
  
  - 'lts/*'

after_success: npm run coverage
