language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  if: os = linux
  if: os = osx
    - node
    - 'lts/*'
  
  if: os = windows
    - latest
    - 'lts/*'

after_success: npm run coverage
