language: node_js

os:
  - linux
  - osx
  - windows
  
if: os = linux
node_js:
  - node
  - 'lts/*'
  
if: os = osx
node_js:
  - node
  - 'lts/*'
    
if: os = windows
node_js:
  - latest
  - 'lts/*'

after_success: npm run coverage
